default: &default
 adapter: mysql2
 encoding: utf8
 pool: 5
 username: <%= ENV['DATABASE_USER'] %>
 password: <%= ENV['DATABASE_PASS'] %>
 host: localhost

development:
 <<: *default
 database: home_meal_development

test: 
 <<: *default
 database: home_meal_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
